FROM dunglas/frankenphp:php8.2

RUN install-php-extensions gd zip pdo_mysql

WORKDIR /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN mkdir -p storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

RUN chown -R www-data:www-data storage bootstrap/cache

ENV SERVER_NAME=:80

CMD ["frankenphp", "php-server", "--root", "/app/public", "--listen", ":80"]